auto:    true

blah:    Hello

brigade:
    name: Code for Asheville
    city:   Asheville
    meetup-link: "#"
    google-group: "https://groups.google.com/a/codeforamerica.org/forum/#!forum/open-asheville"
    github: "https://github.com/openAsheville"
    idea-list: "http://opendatacatalog.ashevillenc.gov/opendata/nominate/?sort=rating_score&dir=desc"

content:
    title: Code for Asheville | A Code for America Brigade
    meetup-invite: "A casual <a href='#'>meetup</a>, usually bi-weekly."
    contact: "Our brigade captains are Scott Barnwell & Dave Michelson (johndoe@example.com or @johndoe)."
    banner: ./images/city_building2.jpg
    projects:
      - name: Project 1
        content: "<a href='example.com'>Example link 1</a>"

      - name: Project 2
        content: "<a href='example.com'>Example link 2</a>"

      - name: Project idea
        content: "<a href='http://opendatacatalog.ashevillenc.gov/opendata/nominate/?sort=rating_score&dir=desc'>List of Future Ideas!</a> Submit your Own Ideas, or Pick One To Help With"

google-analytics:
    use: true
    code: UA-37433852-1